version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    container_name: app_php
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      #DATABASE_URL: "postgresql://symfony:password@db:5432/symfony?serverVersion=13&charset=utf8"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - postgres

  postgres:
    container_name: app_postgres
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data:rw

volumes:
  db_data: